query SearchItems($search: String!, $nextPage: Int) {
  searchItems(input: { search: $search, nextPage: $nextPage }) {
    items {
      tokenAddress
      tokenId
      name
      description
      file
    }
    nextPage
  }
}
