import { AppProvider } from "@/shared/AppProvider/AppProvider";
import "./globals.css";

export const metadata = {
  title: "Flexi Swap",
  description: "Generated by create next app",
  icons: {
    icon: './favicon.ico'
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"bg-bgDefault"}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
