query GetMyTrades($first: Int, $skip: Int, $owner: Bytes!) {
  trades(first: $first, skip: $skip, where: { initiatorAddress: $owner }) {
    id
    initiatorAddress
    createdAt
    givings {
      items {
        metadata {
          tokenAddress
          tokenId
          name
          description
          file
        }
      }
    }
    receivings {
      id
      items {
        metadata {
          tokenId
          tokenAddress
          name
          description
          file
        }
      }
    }
    counterOffers {
      id
      createdAt
      items {
        metadata {
          tokenAddress
          tokenId
          name
          description
          file
        }
      }
      offererAddress
    }
  }
}
