query GetAllTrades($first: Int, $skip: Int) {
  trades(first: $first, skip: $skip, orderBy: createdAt, orderDirection: desc) {
    id
    initiatorAddress
    createdAt
    givings {
      items {
        metadata {
          tokenAddress
          tokenId
          name
          description
          file
        }
      }
    }
    receivings {
      id
      items {
        metadata {
          tokenAddress
          tokenId
          name
          description
          file
        }
      }
    }
  }
}
