query GetMyTrades($first: Int, $skip: Int, $owner: Bytes!) {
  trades(first: $first, skip: $skip, where: { initiatorAddress: $owner }) {
    id
    initiatorAddress
    createdAt
    givings {
      items {
        item {
          tokenId
          tokenAddress
          name
          description
          file
        }
      }
    }
    receivings {
      id
      items {
        item {
          tokenId
          tokenAddress
          name
          description
          file
        }
        collection {
          tokenAddress
          name
          symbol
          logo
          previewItems {
            file
          }
        }
      }
    }
  }
}
